// Normalize generated trees to explicit cell-space root pivots; preserve archived Meshy masters.
import {existsSync} from 'node:fs';
import {createRequire} from 'node:module';import {readFile,writeFile} from 'node:fs/promises';import {createHash} from 'node:crypto';
const req=createRequire(new URL('../model-opt/package.json',import.meta.url));const {NodeIO}=await import(req.resolve('@gltf-transform/core'));const {ALL_EXTENSIONS}=await import(req.resolve('@gltf-transform/extensions'));const {getBounds,compactPrimitive,tangents,unweld,weld}=await import(req.resolve('@gltf-transform/functions'));
const {generateTangents}=await import(req.resolve('mikktspace'));
const io=new NodeIO().registerExtensions(ALL_EXTENSIONS),records=[];
for(const [id,height] of [['tree22',1.43],['tree10',1.25]]){
 const input='.cache/environment/'+id+'/foliage.glb';if(!existsSync(input))continue;const doc=await io.read(input),scene=doc.getRoot().getDefaultScene(),bounds=getBounds(scene),scale=height/(bounds.max[1]-bounds.min[1]);
 const spread=id==='tree22'?1.65:1.25;const root=doc.createNode(id+' root pivot').setScale([scale*spread,scale,scale*spread]).setTranslation([-(bounds.min[0]+bounds.max[0])/2*scale*spread,-bounds.min[1]*scale,-(bounds.min[2]+bounds.max[2])/2*scale*spread]);for(const n of [...scene.listChildren()]){scene.removeChild(n);root.addChild(n);}scene.addChild(root);
 let removedDegenerateTriangles=0;for(const mesh of doc.getRoot().listMeshes())for(const p of mesh.listPrimitives()){const pos=p.getAttribute('POSITION'),a=p.getIndices().getArray(),keep=[];for(let i=0;i<a.length;i+=3){const v0=pos.getElement(a[i],[]),v1=pos.getElement(a[i+1],[]),v2=pos.getElement(a[i+2],[]),u=v1.map((v,j)=>v-v0[j]),v=v2.map((v,j)=>v-v0[j]);if(Math.hypot(u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0])<1e-12){removedDegenerateTriangles++;continue;}keep.push(a[i],a[i+1],a[i+2]);}p.getIndices().setArray(new Uint32Array(keep));compactPrimitive(p);}
let repairedNormals=0;for(const mesh of doc.getRoot().listMeshes())for(const p of mesh.listPrimitives()){const pos=p.getAttribute('POSITION'),n=p.getAttribute('NORMAL'),a=p.getIndices().getArray();for(let i=0;i<a.length;i+=3){const vs=[0,1,2].map(j=>pos.getElement(a[i+j],[])),u=vs[1].map((v,j)=>v-vs[0][j]),v=vs[2].map((v,j)=>v-vs[0][j]),cross=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]],len=Math.hypot(...cross);for(let j=0;j<3;j++)if(Math.hypot(...n.getElement(a[i+j],[]))<.9&&len){n.setElement(a[i+j],cross.map(x=>x/len));repairedNormals++;}}}await doc.transform(unweld(),tangents({generateTangents,overwrite:true}),weld());
 const dst='assets/hd/environment/'+id+'.glb';await io.write(dst,doc);const bytes=await readFile(dst),task=JSON.parse(await readFile('.cache/environment/'+id+'/task.json')),request=JSON.parse(await readFile('.cache/environment/'+id+'/request.json'));const report=JSON.parse(await readFile('.cache/environment/'+id+'/foliage.json'));
 records.push({id,type:'tree',file:id+'.glb',unit:'cell',cellSize:1,up:'+Y',forward:'+Z',pivot:[0,0,0],footprintCells:[1,1],heightCells:height,rootMethod:'Bottom of generated mesh, horizontal center of bounds; approximate root center requires visual validation',sourceImageAnchorWarning:'Original converted sprite anchors include empty lower space; Canvas placement calibration is separate from GLB root pivot',triangles:report.after.triangles-removedDegenerateTriangles,removedDegenerateTriangles,repairedNormals,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex'),master:'.cache/environment/'+id+'/master.glb',pipeline:'built-in ImageGen → Meshy image-to-3D → local meshoptimizer → MikkTSpace → 1K WebP',taskId:task.id||task.result,request,optimization:report,normalization:{inputBounds:bounds,scale,spread},inference:'Backside, branch depths and root geometry generated from one source view; no wind rig',teamColor:false,lod:'30k base; instances share mesh and textures; lower LOD not yet delivered'});
}
await writeFile('assets/hd/environment/trees.json',JSON.stringify({description:'Generated tree provenance and actual runtime metrics.',assets:records},null,2)+'\n');
