// Real GLB decoding, four orientations, pitch, repeat instances and Canvas engine acceptance.
import {chromium} from '@playwright/test';import {mkdir,writeFile,readFile} from 'node:fs/promises';import assert from 'node:assert/strict';
await mkdir('.cache/environment/verification',{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4186/');await page.waitForFunction(()=>window.environment?.ready,{timeout:180000});
const metrics=await page.evaluate(()=>window.environment.metrics);assert.equal(Object.keys(metrics).length,6);for(const id of ['tree22','tree10']){assert.ok(metrics[id].bounds[0]>.3&&metrics[id].bounds[2]>.3,'Tree must have real depth');assert.ok(metrics[id].triangles>1000);}for(const id of ['plateau','ramp'])assert.ok(metrics[id].bounds[1]>.4);
for(const angle of ['north','east','south','west']){await page.getByTestId('view-'+angle).click();await page.waitForTimeout(200);await page.screenshot({path:'.cache/environment/verification/'+angle+'.png'});}
await page.getByTestId('pitch').click();await page.screenshot({path:'.cache/environment/verification/top.png'});
const requests=[];await page.close();const canvas=await browser.newPage({viewport:{width:1440,height:1000}});canvas.on('request',r=>requests.push(r.url()));canvas.on('pageerror',e=>errors.push(e.message));await canvas.goto('http://127.0.0.1:4186/canvas.html');await canvas.waitForFunction(()=>window.environmentCanvas?.ready,{timeout:180000});await canvas.screenshot({path:'.cache/environment/verification/canvas.png'});await canvas.getByTestId('toggle').click();await canvas.screenshot({path:'.cache/environment/verification/canvas-original.png'});assert.ok(!requests.some(u=>u.endsWith('.glb')||u.includes('three')),'Canvas must consume baked art only');assert.deepEqual(errors,[]);
const mods=JSON.parse(await readFile('assets/hd/environment/modules.json'));const a=mods.assets.find(x=>x.id==='ramp'),b=mods.assets.find(x=>x.id==='plateau');assert.deepEqual(a.edges.south,b.edges.north);assert.deepEqual(a.edges.north,[0,0]);
await writeFile('.cache/environment/verification/report.json',JSON.stringify({metrics,errors,canvasGLBRequests:0,edgeConnection:'ramp south = plateau north',screenshots:['north','east','south','west','top','canvas','canvas-original']},null,2));await browser.close();console.log('Six GLB decodes, four views, pitch, Canvas and module edges passed');
