// Add editable skin/clip data to existing 30K geometry without regenerating shapes or losing embedded PBR.
import fs from 'node:fs/promises';import crypto from 'node:crypto';import {Matrix4}from'three';
import {fitSquidRig} from './squid-rig.mjs';
import {readGLB,editor}from'./glb.mjs';import{makeRig,weights,pose}from'./rigs.mjs';import{catalogs,fps}from'./motion-catalog.mjs';
for(const[id,dir]of Object.entries({rock:'rocketeer',sqd:'squid'})){
 const root='.cache/four-assets/'+dir,input=await readGLB(root+'/30k.glb'),{g}=input,e=editor(input),primitive=g.meshes[0].primitives[0],squid=id==='sqd'?fitSquidRig(e.values(primitive.attributes.POSITION),e.values(primitive.indices)):null,joints=squid?.joints||makeRig(id),base=g.nodes.length;
 g.nodes.push(...joints.map(j=>({name:j.name,translation:j.parent<0?j.p:j.p.map((v,k)=>v-joints[j.parent].p[k]),children:[]})));joints.forEach((j,i)=>{if(j.parent>=0)g.nodes[base+j.parent].children.push(base+i);});g.scenes[g.scene||0].nodes.push(base);
 const inverses=joints.flatMap(j=>new Matrix4().makeTranslation(...j.p.map(v=>-v)).toArray());g.skins=[{name:id+' authored skeleton',joints:joints.map((_,i)=>base+i),skeleton:base,inverseBindMatrices:e.add(inverses,16)}];
 let vertices=0,triangles=0;for(const n of g.nodes)if(n.mesh!==undefined){n.skin=0;for(const p of g.meshes[n.mesh].primitives){const pos=e.values(p.attributes.POSITION),ji=[],wt=[];for(let i=0;i<pos.length;i+=3){const w=squid?(squid.vertexWeights.get(i/3)||[[0,1]]):weights(id,pos.slice(i,i+3),joints);ji.push(...w.map(w=>w[0]),...Array(4-w.length).fill(0));wt.push(...w.map(w=>w[1]),...Array(4-w.length).fill(0));}p.attributes.JOINTS_0=e.add(ji,4,5123);p.attributes.WEIGHTS_0=e.add(wt,4);vertices+=pos.length/3;triangles+=g.accessors[p.indices].count/3;}}
 g.animations=[];for(const[action,s]of Object.entries(catalogs[id])){const count=s.source[1],duration=count/fps,phases=[...new Set([...Array.from({length:Math.ceil(duration*60)+1},(_,i)=>i/Math.ceil(duration*60)),...Array.from({length:count},(_,i)=>count===1?0:i/(s.loop?count:count-1))])].sort((a,b)=>a-b),time=e.add(phases.map(t=>t*duration),1),frames=phases.map(p=>pose(id,action,p,joints)),clip={name:action,channels:[],samplers:[],extras:{...s,duration,fps,source:'authored source-referenced reconstruction'}};for(let j=0;j<joints.length;j++)for(const prop of ['rotation','translation']){if(prop==='translation'&&j>0)continue;const data=frames.flatMap(p=>p[j][prop]);clip.channels.push({sampler:clip.samplers.push({input:time,output:e.add(data,prop==='rotation'?4:3),interpolation:'LINEAR'})-1,target:{node:base+j,path:prop}});}g.animations.push(clip);}
 g.asset.extras={...g.asset.extras,rigRecipe:'tools/four-assets/rigs.mjs',sourceAxes:'Y up, original Meshy +Z front',reference:'tools/four-assets/motion-reference.md'};
 const bytes=e.finish(),hash=b=>crypto.createHash('sha256').update(b).digest('hex');await fs.writeFile(root+'/actions.glb',bytes);await fs.copyFile(root+'/actions.glb','.cache/four-assets/candidate/models/'+id+'.glb');const report={inputSha256:hash(input.bytes),sha256:hash(bytes),bytes:bytes.length,triangles,vertices,joints:joints.length,clips:g.animations.map(a=>a.name),sequences:catalogs[id],fps,materialsPreserved:JSON.stringify(g.materials)===JSON.stringify(input.g.materials),limitations:['Authored approximation: SHP does not recover depth or original skeleton','Rocketeer ground-only source sequences are source fallback; BalloonHover unit uses air actions','12 fps preview convention, not verified original executable timing','Squid occluded arm depth and contact with ships inferred; no finger rig on Rocketeer']};await fs.writeFile(root+'/motion-manifest.json',JSON.stringify(report,null,2)+'\n');console.log(id,report.triangles,report.joints,report.clips.length,report.bytes);
}
