import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
const renderer=new T.WebGLRenderer({alpha:true,antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(1);renderer.setClearColor(0,0);renderer.toneMapping=T.NeutralToneMapping;renderer.toneMappingExposure=1;
const scene=new T.Scene();scene.add(new T.HemisphereLight('#d2d9e8','#454750',2));const sun=new T.DirectionalLight('#fff6e8',2.4);sun.position.set(30,55,25);scene.add(sun);
const room=new RoomEnvironment(),pmrem=new T.PMREMGenerator(renderer),env=pmrem.fromScene(room,0);scene.environment=env.texture;scene.environmentIntensity=.55;room.dispose();pmrem.dispose();
const cam=new T.OrthographicCamera(-1,1,1,-1,.01,10000);const loader=new GLTFLoader();let current;
const specs={mtnk:{fw:128,fh:128,ax:64,ay:64,frames:16,columns:8,targetWidth:100,targetHeight:80,turn:Math.PI},tany:{fw:130,fh:110,ax:65,ay:55,frames:8,columns:8,targetWidth:30,targetHeight:34.16,turn:0},gacnst:{fw:284,fh:226,ax:142,ay:166,frames:1,columns:1,targetWidth:235,targetHeight:202,turn:0},nanrct:{fw:276,fh:188,ax:138,ay:128,frames:1,columns:1,targetWidth:228,targetHeight:168,turn:0}};
window.bake=async id=>{if(current)scene.remove(current);const s=specs[id],gltf=await loader.loadAsync(import.meta.env.BASE_URL+'models/'+id);const model=gltf.scene;model.updateMatrixWorld(true);const box=new T.Box3().setFromObject(model),center=box.getCenter(new T.Vector3());model.position.set(-center.x,-box.min.y,-center.z);current=new T.Group();current.add(model);scene.add(current);let triangles=0;model.traverse(o=>{if(o.isMesh)triangles+=(o.geometry.index?.count??o.geometry.attributes.position.count)/3;});
// 30 degree elevation yields the main renderer's 60x30 diamond projection.
cam.position.set(100,100*Math.sqrt(2/3),100);cam.lookAt(0,0,0);cam.updateMatrixWorld();const view=cam.matrixWorldInverse;
let left=Infinity,right=-Infinity,top=-Infinity,bottom=Infinity;
for(let f=0;f<s.frames;f++){current.rotation.y=s.turn-f/s.frames*Math.PI*2;current.updateMatrixWorld(true);const b=new T.Box3().setFromObject(current);for(const x of [b.min.x,b.max.x])for(const y of [b.min.y,b.max.y])for(const z of [b.min.z,b.max.z]){const v=new T.Vector3(x,y,z).applyMatrix4(view);left=Math.min(left,v.x);right=Math.max(right,v.x);top=Math.max(top,v.y);bottom=Math.min(bottom,v.y);}}
const pixelsPerUnit=Math.min(s.targetWidth/(right-left),s.targetHeight/(top-bottom),(s.ay-5)/top,(s.fh-s.ay-3)/Math.max(-bottom,.0001));
const density=4,W=s.fw*density,H=s.fh*density;renderer.setSize(W,H);cam.left=-s.ax/pixelsPerUnit;cam.right=(s.fw-s.ax)/pixelsPerUnit;cam.top=s.ay/pixelsPerUnit;cam.bottom=-(s.fh-s.ay)/pixelsPerUnit;cam.updateProjectionMatrix();
const sheet=document.createElement('canvas');sheet.width=W*s.columns;sheet.height=H*Math.ceil(s.frames/s.columns);const ctx=sheet.getContext('2d');
for(let f=0;f<s.frames;f++){current.rotation.y=s.turn-f/s.frames*Math.PI*2;renderer.render(scene,cam);ctx.drawImage(renderer.domElement,f%s.columns*W,Math.floor(f/s.columns)*H);await new Promise(requestAnimationFrame);}
const data=sheet.toDataURL('image/png');const metadata={src:'/sprites/'+id+'.png',width:sheet.width,height:sheet.height,frameWidth:W,frameHeight:H,frames:s.frames,columns:s.columns,anchorX:s.ax*density,anchorY:s.ay*density,pixelRatio:density,facings:s.frames};if(id==='tany')metadata.sequences={ready:[0,1,1]};if(id==='gacnst'||id==='nanrct')metadata.foundation=[4,4];
const textures=new Set(),materials=new Set(),geos=new Set();model.traverse(o=>{if(o.geometry)geos.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material])if(m){materials.add(m);Object.values(m).forEach(v=>{if(v?.isTexture)textures.add(v);});}});scene.remove(current);geos.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>{t.dispose();t.source.data?.close?.();});current=null;return {data,metadata,triangles,pixelsPerUnit};};
