import {chromium} from '@playwright/test';
import {writeFile,mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
await mkdir('.cache/viewer-tests',{recursive:true});
const b=await chromium.launch({channel:'chrome',headless:true});
try{const p=await b.newPage({viewport:{width:1500,height:1000},deviceScaleFactor:2,locale:'zh-CN'});const errors=[],requests=[];p.on('pageerror',e=>{errors.push(e.message);console.log(e.message);});p.on('request',r=>requests.push(r.url()));await p.addInitScript(()=>{window.__contexts=[];const get=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){window.__contexts.push(type);return get.call(this,type,...args);};});await p.goto(process.env.PREVIEW_URL||'http://127.0.0.1:4175/canvas/');await p.waitForFunction(()=>window.__hd?.ready,{},{timeout:60000});await p.waitForTimeout(1000);await p.screenshot({path:'.cache/viewer-tests/canvas-hd.png'});const state=await p.evaluate(()=>({contexts:[...new Set(window.__contexts)],status:__hd.game.status,actors:__hd.actors.length,renderClass:__hd.renderer.constructor.name,zoom:__hd.renderer.zoom}));console.log(state);assert(state.contexts.every(x=>x==='2d'));assert(!requests.some(u=>/\.glb|three.*\.js/.test(u)));assert.equal(state.renderClass,'BattlefieldRenderer');
const density=await p.evaluate(()=>{const ctx=__hd.renderer.ctx,draw=ctx.drawImage,calls=[];ctx.drawImage=function(...args){if(args.length===9&&args[3]>=400)calls.push(args.slice(1));return draw.apply(this,args);};__hd.renderer.draw();ctx.drawImage=draw;return calls;});assert(density.length>=8);assert(density.every(a=>a[2]/a[6]===4&&a[3]/a[7]===4));
await p.click('#toggle');await p.screenshot({path:'.cache/viewer-tests/canvas-original.png'});await p.click('#toggle');await p.click('#zoom');await p.screenshot({path:'.cache/viewer-tests/canvas-hd-close.png'});
const pos=await p.evaluate(()=>{const e=__hd.actors.find(e=>e.type==='apocalypse');return {...__hd.renderer.toScreen(e.x,e.y),id:e.id,x0:e.x,y0:e.y};});const box=await p.locator('#battle').boundingBox();await p.mouse.click(box.x+pos.x,box.y+pos.y);assert(await p.evaluate(id=>__hd.renderer.selection.has(id),pos.id));const target=await p.evaluate(()=>__hd.renderer.toScreen(22,25));await p.mouse.click(box.x+target.x,box.y+target.y,{button:'right'});await p.waitForTimeout(1800);const moved=await p.evaluate(id=>{const e=__hd.game.getEntity(id);return {x:e.x,y:e.y,path:e.path.length,order:e.order};},pos.id);assert(Math.hypot(moved.x-pos.x0,moved.y-pos.y0)>.1);
await p.click('#reset');const a0=await p.evaluate(()=>__hd.actors[2].angle);await p.click('#rotate');assert.notEqual(await p.evaluate(()=>__hd.actors[2].angle),a0);assert.deepEqual(errors,[]);await writeFile('.cache/viewer-tests/verification.json',JSON.stringify({state,densityDraws:density.length,canvasOnly:true,noRuntimeGLB:true,selection:true,movement:moved,rotation:true,errors},null,2));console.log('PASS');}finally{await b.close();}
